<div class="flexslider">
    <ul class="slides">
        <?php foreach ($this->getBannersContent() as $banner):?>
            <li>
                <a href="<?php echo $banner->getUrl() ?>">
                <img
                        src="<?php echo $this->getImageSrc().$banner->getImage()?>"
                        alt="<?php echo $this->htmlEscape($banner->getTitle()); ?>"
                        title="<?php echo $this->escapeHtml($banner->getTitle()); ?>">
            </a>
        </li>
        <?php endforeach;?>
    </ul>
</div>


<script type="text/javascript">
    var  $j = jQuery.noConflict();
    $j(document).ready(function() {
        $j('.flexslider').flexslider({
            animation: "slide"
            });
        });
</script>
