<? if (count($this->getBannersContent()) != 0) :?>
    <div class="flexslider">
        <ul class="slides">
            <?php foreach ($this->getBannersContent() as $banner):?>
                <li>
                    <a href="<?php echo $banner->getUrl() ?>">
                        <img
                                src="<?php echo $this->getBaseUr().$banner->getImage()?>"
                                alt="<?php echo $this->htmlEscape($banner->getTitle()); ?>"
                                title="<?php echo $this->escapeHtml($banner->getTitle()); ?>">
                    </a>
                </li>

            <?php endforeach;?>

        </ul>
    </div>
<?php endif;?>
